name: build_and_publish.yaml # try to keep name the same as current file name (build.yaml in this case)
on:
  workflow_run:
    # Depends on these workflows
    workflows: ["tests.yaml"]
    branches: [main]
    types:
      - completed
jobs:
  build:
    # Check if the workflow_run was successful and the commit message starts with "[publish]"
    if: (github.event.workflow_run.conclusion == 'success') && (startsWith(github.event.workflow_run.head_commit.message, '[publish] '))
    uses: ./.github/workflows/build.yaml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
      - name: Download all prebuilds
        uses: actions/download-artifact@v4
        with:
          path: prebuilds
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: '#major'
          minor-wording: '#minor'
          patch-wording: '#patch'
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
