on:
  push:
    tags:
      - "v*.*.*"
jobs:
  #create_release:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Create GitHub Release
  #      id: create_release
  #      uses: actions/create-release@v1.1.4
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      with:
  #        tag_name: ${{ github.ref_name }}
  #        release_name: ${{ github.ref_name }}
  #        draft: false
  #        prerelease: false
  build:
    #needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
          registry-url: "https://registry.npmjs.org/"
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Copy libz3.dll into prebuild folder (Windows only)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          mkdir prebuilds
          DLL_SOURCE=third_party/z3/lib/win32-x64/libz3.dll
          DLL_TARGET=prebuilds/libz3.dll
          cp "$DLL_SOURCE" "$DLL_TARGET"
      - name: Build and upload prebuild
        run: |
          npm run prebuild -- -u ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
