on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Get Prebuild Name
        id: prebuild
        shell: bash
        run: |
          PREBUILD_FOLDER_NAME=$(node -p "require('os').platform() + '-' + require('os').arch()")
          echo "PREBUILD_FOLDER_NAME=$PREBUILD_FOLDER_NAME" >> $GITHUB_OUTPUT

      - name: Copy libz3.dll into prebuild folder (Windows only)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          DLL_SOURCE=third_party/z3/lib/win32-x64/libz3.dll
          DLL_TARGET=prebuilds/${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }}/libz3.dll
          cp "$DLL_SOURCE" "$DLL_TARGET"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Build prebuild
        run: npm run prebuild -- --tag ${{ github.ref_name }} --upload-all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
