name: tests.yaml
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test-js:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Description of job
        shell: bash
        run: echo "Transitively tests the native C++ wrapper code by way of testing built .node files in JS for each platform we support."
      - name: Get {platform}-{arch} name
        id: prebuild
        shell: bash
        run: |
          PREBUILD_FOLDER_NAME=$(node -p "require('os').platform() + '-' + require('os').arch()")
          echo "PREBUILD_FOLDER_NAME=$PREBUILD_FOLDER_NAME" >> $GITHUB_OUTPUT
      - name: Compute cache key
        id: cache-key
        run: echo "hash=${{ hashFiles('src/**/*.cpp', 'src/**/*.hpp', 'third_party/**/*.*') }}" >> $GITHUB_OUTPUT
      - name: Cache ${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }} build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: prebuilds/${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }}
          key: build-${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }}-${{ steps.cache-key.outputs.hash }}
          restore-keys: |
            build-${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }}-${{ steps.cache-key.outputs.hash }}
      - name: Install dependencies (if no cache)
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts
      - name: Build (if no cache)
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run prebuildify
      - name: Copy libz3.dll into prebuild folder (Windows only) (if no cache)
        if: (steps.cache-build.outputs.cache-hit != 'true') && (matrix.os == 'windows-latest')
        shell: bash
        run: |
          DLL_SOURCE=third_party/z3/lib/${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }}/libz3.dll
          DLL_TARGET=prebuilds/${{ steps.prebuild.outputs['PREBUILD_FOLDER_NAME'] }}/libz3.dll
          cp "$DLL_SOURCE" "$DLL_TARGET"
      - name: Run JS tests
        run: npm run test:js
  test-underlying-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Job description
        shell: bash
        run: echo "Tests the underlying C++ predictors. Meaning, the underlying code that our wrappers wrap, so we can expose underlying to Node."
      - name: Cache CMake tests/build/ directory
        uses: actions/cache@v4
        with:
          path: tests/build/
          key: test-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cpp', '**/*.hpp') }}
          restore-keys: |
            test-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cpp', '**/*.hpp') }}
      - name: Build and run tests
        run: npm test
