name: tests.yaml # try to keep name the same as current file name (tests.yaml in this case)
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached CMake tests/build/ directory
        id: cache-tests-build
        uses: actions/cache/restore@v4
        with:
          path: tests/build/
          key: cmake-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cpp', '**/*.hpp') }}
          restore-keys: |
            cmake-${{ runner.os }}
          lookup-only: false
      - name: Cache CMake tests/build/ directory
        uses: actions/cache@v4
        with:
          path: tests/build/
          key: cmake-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cpp', '**/*.hpp') }}
          restore-keys: |
            cmake-${{ runner.os }}
          lookup-only: false
      - name: Build and run tests
        run: npm test