name: tests.yaml # try to keep name the same as current file name (tests.yaml in this case)
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  test_js:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Run JS tests
        run: npm run test:js
  test_cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache CMake tests/build/ directory
        uses: actions/cache@v4
        with:
          path: tests/build/
          key: cmake-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cpp', '**/*.hpp') }}
          restore-keys: |
            cmake-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cpp', '**/*.hpp') }}
      - name: Build and run tests
        run: npm test